name: SimpleUHC
version: '${project.version}'
main: fr.rammex.simpleuhc.SimpleUHC
depend:
  - GameAPI
  - GUIToolkit
commands:
  team:
    description: Manage teams
  simpleuhc:
    description: Main command for SimpleUHC
    permission: simpleuhc.admin
  teaminventory:
    description: Team Inventory
    aliases:
      - ti
      - bp
  tc:
    description: Toggle team chat mode
    aliases:
      - teamchat
  tcc:
    description: Send your coordinates to team chat
    aliases:
      - teamcoords
  uhcconfig:
    description: Manage UHC configurations
    permission: simpleuhc.admin
    aliases:
      - config