name: SimpleUHC
version: '${project.version}'
main: fr.rammex.simpleuhc.SimpleUHC
depend:
  - GameAPI
  - GUIToolkit
commands:
  team:
    description: Manage teams
  simpleuhc:
    description: Main command for SimpleUHC
    permission: simpleuhc.admin